def get_label(confidence: float, attribution: str) -> str:
    """Maps confidence score + attribution to the exact label text from planning.md."""
    if attribution == "likely_ai":
        pct = round(confidence * 100)
        return (
            f"⚠️ Likely AI-generated\n\n"
            f"Our system detected strong indicators that this content may have been produced "
            f"with an AI writing tool. Confidence: {pct}% AI.\n\n"
            f"This label reflects automated analysis and may not be accurate. If you wrote "
            f"this yourself, you can submit an appeal below — we'll review it and update "
            f"this classification."
        )
    elif attribution == "uncertain":
        return (
            "🔍 Authorship unclear\n\n"
            "We weren't able to confidently determine whether this content was written by "
            "a human or generated by an AI tool. Our signals disagreed or were too weak "
            "to make a reliable call.\n\n"
            "No action will be taken based on this result. You can still submit an appeal "
            "if you'd like to add context about how this was written."
        )
    else:  # likely_human
        pct = round((1 - confidence) * 100)
        return (
            f"✅ Appears human-written\n\n"
            f"Our analysis found no strong indicators of AI generation in this content. "
            f"Confidence: {pct}% human-authored."
        )
